apiVersion: v1
kind: PersistentVolume
metadata:
  name: sql-script-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  azureBlob:
    secretName: azure-secret
    secretNamespace: default
    container: ${AZURE_CONTAINER_NAME}
    storageAccount: ${AZURE_STORAGE_ACCOUNT_NAME}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sql-script-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:latest
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: mysql-root-password
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: sql-script
              mountPath: /docker-entrypoint-initdb.d/
              readOnly: true
      volumes:
        - name: sql-script
          persistentVolumeClaim:
            claimName: sql-script-pvc
