apiVersion: v1
kind: PersistentVolume
metadata:
  name: sql-script-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  azureFile:
    secretName: azure-secret # Secret with Azure Storage Account credentials
    secretNamespace: default # Namespace where the secret is stored
    shareName: ${AZURE_CONTAINER_NAME} # Azure File share name
    readOnly: false # Set to true if you only need read access
  persistentVolumeReclaimPolicy: Retain # Optionally set to Retain to keep data even if PVC is deleted
