apiVersion: v1
kind: PersistentVolume
metadata:
  name: sql-script-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  azureFile:
    secretName: azure-secret # Secret that holds Azure Storage credentials
    secretNamespace: default # Namespace where the secret is stored
    shareName: "$(azurefilename)" # Azure file share name as a string
    readOnly: false
