apiVersion: v1
kind: PersistentVolume
metadata:
  name: sql-script-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  azureFile:
    secretName: azure-secret # Secret that holds Azure Storage credentials
    secretNamespace: default # Namespace where the secret is stored
    shareName:
      valueFrom:
        secretKeyRef:
          name: azure-secret
          key: azurefilename
    readOnly: false # Set to true if you want read-only access
