apiVersion: v1
kind: PersistentVolume
metadata:
  name: sql-script-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  azureFile:
    secretName: azure-secret # Secret that holds Azure Storage credentials
    secretNamespace: default # Namespace where the secret is stored
    shareName: azurecontainername # Use the actual name as per the secret key
    readOnly: false # Set to true if you want read-only access
  persistentVolumeReclaimPolicy: Retain
