apiVersion: v1
kind: PersistentVolume
metadata:
  name: sql-script-pv
spec:
  capacity:
    storage: 50Mi
  accessModes:
    - ReadWriteOnce
  storageClassName: default
  azureFile:
    secretName: azure-secret
    shareName: "my-sql-file-container"
