name: Deploy MySQL to Kubernetes

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up kubectl to interact with the Kubernetes cluster
      - name: Set up kubectl
        uses: azure/setup-kubectl@v1
        with:
          kubeconfig: ${{ secrets.KUBE_CONFIG }}

      # Step 3: Create Kubernetes Secrets from GitHub Secrets
      - name: Create Kubernetes Secrets
        run: |
          kubectl create secret generic azure-secret \
            --from-literal=azurestorageaccountname=${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }} \
            --from-literal=azurestorageaccountkey=${{ secrets.AZURE_STORAGE_ACCOUNT_KEY }} \
            --dry-run=client -o yaml | kubectl apply -f -
          
          kubectl create secret generic mysql-secret \
            --from-literal=mysql-root-password=${{ secrets.MYSQL_ROOT_PASSWORD }} \
            --dry-run=client -o yaml | kubectl apply -f -

      # Step 4: Apply MySQL deployment
      - name: Apply Kubernetes MySQL deployment
        run: |
          kubectl apply -f k8s/mysql-deployment.yml

      # Step 5: Check MySQL pod status
      - name: Check MySQL pod status
        run: |
          kubectl get pods -l app=mysql
