name: Deploy MySQL to Kubernetes with Azure Files

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up kubectl to interact with the Kubernetes cluster
      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: "latest"

      # Step 3: Configure kubectl using kubeconfig from GitHub Secrets
      - name: Configure kubectl using kubeconfig
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBE_CONFIG }}" > $HOME/.kube/config

      # Step 4: Create Kubernetes Secrets from GitHub Secrets
      - name: Create Kubernetes Secrets
        run: |
          # Create Azure storage secrets for PV
          kubectl create secret generic azure-secret \
            --from-literal=azurestorageaccountname=${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }} \
            --from-literal=azurestorageaccountkey=${{ secrets.AZURE_STORAGE_ACCOUNT_KEY }} \
            --from-literal=azurecontainername=${{ secrets.AZURE_STORAGE_CONTAINER_NAME }} \
            --dry-run=client -o yaml | kubectl apply -f -

          # Create MySQL root password secret
          kubectl create secret generic mysql-secret \
            --from-literal=mysql-root-password=${{ secrets.MYSQL_ROOT_PASSWORD }} \
            --dry-run=client -o yaml | kubectl apply -f -

      # Step 5: Apply PersistentVolume (PV) and PersistentVolumeClaim (PVC)
      - name: Apply PersistentVolume and PersistentVolumeClaim
        run: |
          kubectl apply -f k8s/persistent-volume.yml
          kubectl apply -f k8s/persistent-volume-claim.yml

      # Step 6: Apply MySQL deployment
      - name: Apply Kubernetes MySQL deployment
        run: |
          kubectl apply -f k8s/mysql-deployment.yml  # Ensure the correct file path for your MySQL deployment

      # Step 7: Apply MySQL Service
      - name: Apply MySQL service
        run: |
          kubectl apply -f k8s/mysql-service.yml  # Ensure the correct file path for your MySQL service

      # Step 8: Clear kubeconfig file for security
      - name: Clear kubeconfig file
        run: |
          rm -f $HOME/.kube/config

      # Step 9: Check MySQL pod status
      - name: Check MySQL pod status
        run: |
          kubectl get pods -l app=mysql
