name: Deploy MySQL to Kubernetes

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up kubectl to interact with the Kubernetes cluster
      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: "latest"

      # Step 3: Configure kubectl using kubeconfig
      - name: Configure Kubectl using kubconfig
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBE_CONFIG }}" > $HOME/.kube/config

      # Step 4: Create Kubernetes Secrets from GitHub Secrets
      - name: Create Kubernetes Secrets
        run: |
          kubectl create secret generic azure-secret \
            --from-literal=azurestorageaccountname=${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }} \
            --from-literal=azurestorageaccountkey=${{ secrets.AZURE_STORAGE_ACCOUNT_KEY }} \
            --from-literal=azurecontainername=${{ secrets.AZURE_STORAGE_CONTAINER_NAME }} \
            --dry-run=client -o yaml | kubectl apply -f -

          kubectl create secret generic mysql-secret \
            --from-literal=mysql-root-password=${{ secrets.MYSQL_ROOT_PASSWORD }} \
            --dry-run=client -o yaml | kubectl apply -f -

      # Step 5: Apply MySQL deployment
      - name: Apply Kubernetes MySQL deployment
        run: |
          kubectl apply -f k8s/mysql-deployment.yml

      # Step 6: Clear kubeconfig file
      - name: Clear kubeconfig file
        run: |
          rm -f $HOME/.kube/config
